#!/usr/bin/env python3
"""Assemble an rFactor 2 ModDev track folder from the 3DSimED export.

Lays the files out like the ModDev sample track (Joesville), which this script also takes the
surface-physics file and sky from:

    <out>/TeessideKarting/
        TeessideKarting.tdf                    surface physics (copied from the sample track)
        Assets/GMT/*.gmt                       your exported meshes + the sample sky dome
        Assets/Maps/*.dds                      textures
        Teesside_Karting/Teesside_Karting.gdb  track info (name, location, length, time zone...)
        Teesside_Karting/Teesside_Karting.scn  scene: search paths, sun, fog + every exported instance
        Teesside_Karting/Teesside_Karting.AIW  placeholder copy of the sample track's AIW (rF2 won't list a
                                               layout without one) unless an AIW is already there
        TeessideKartingIcon.dds, Teesside_Karting/*icon*, *Thmb.tga, *_loading.jpg
                                               track-map images like the sample track's (venue icon,
                                               list icon, thumbnail, loading screen)
        Teesside_Karting/*.cam, *.wet, *.rrbin placeholder copies of the sample's cameras, weather and
                                               RealRoad presets, unless the layout has its own

Copy <out>/TeessideKarting into ...\\steamapps\\common\\rFactor 2\\ModDev\\Locations\\, or point
--out straight at that Locations folder.

    python tools/make_track_folder.py                         # writes dist/Locations/TeessideKarting
    python tools/make_track_folder.py --out "C:/.../rFactor 2/ModDev/Locations"
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

from pyproj import Transformer

from patch_scn import patch
from png_to_dds import write_dds

SCN_HEADER = """CUBEASF

//-------------------------------------------------------
// Generated by tools/make_track_folder.py. Header layout copied from the ModDev sample track.
//-------------------------------------------------------

{search_paths}

//-------------------------------------------------------

MASFile=COMMONMAPS.MAS

//-------------------------------------------------------

View=mainview
{{
  Clear=False
  Color=(0, 0, 0)
  Size=(1.00, 1.00) Center=(0.5, 0.5)
  FOV=(77.75, 31.25)
  ClipPlanes=(0.50, 1500.00)
  View=rearview
  {{
    Clear=False
    Color=(0, 0, 0)
    Size=(0.200, 0.100) Center=(0.50, 0.01)
    FOV=(62.5, 62.5)
    ClipPlanes=(0.50, 150.00)
  }}
}}

//-------------------------------------------------------

GroupMethod=Dynamic
MaxShadowRange=(450.00)
AmbientColor=(126, 126, 126)
ReflectPlane=(0.000, 1.000, 0.000, 0.000)

FogMode=LINEAR FogIn=(50.00) FogOut=(5000.00) FogDensity=(0.00015) FogColor=(205, 215, 235)

//-------------------------------------------------------
//---------------------LIGHTING--------------------------
//-------------------------------------------------------

Light=Direct00
{{
 Type=Directional Color=(220, 220, 220) Dir=(0.5, -0.9, 0.5)
}}

//-------------------------------------------------------
//---------------------TRACK-----------------------------
//-------------------------------------------------------

"""

SKY_INSTANCE = """
Instance=SkyBoxi
{
  Planes=(4) ReflectPlane=(0.000, 1.000, 0.000, 0.000)
  MeshFile=SkyBoxi.gmt CollTarget=False HATTarget=False Reflect=True
}
"""

GDB = """{layout}
{{
  Filter Properties = rFRS TMOD NSCRS IndyCar
  Attrition = 30
  TrackName = {track_name}
  EventName = {track_name}
  VenueName = {venue}
  VenueIcon = {folder}\{folder}Icon.dds
  Location = Middlesbrough, England, UK
  Length = {km:.3f} KM / {miles:.2f} Miles
  TrackType = Kart Track
  TerrainDataFile=..\\{folder}.tdf
  HeadlightsRequired = false
  Max Vehicles = 20

  FormationAndStart=2         // formation lap with rolling start
  PitlaneBoundary = 0         // no pit lane modelled yet: request a stop before being serviced
  GarageDepth = 2.0
  RacePitKPH = 30
  NormalPitKPH = 30
  FormationSpeedKPH = 40
  PitsClosedLaps = 2
  MinimumYellowLaps = 2
  LeadYellowLaps = 2
  TestDayStart = 13:00
  RaceLaps = 15
  RaceTime = 30

  NumStartingLights = 2

  Latitude = {lat:.5f}         // degs from Equator (positive is Northern Hemisphere)
  Longitude = {lon:.5f}        // degs from GMT (positive is East)
  Altitude = {alt:.1f}             // meters above sea level
  RaceDate = June 14, 2026
  TimezoneRelativeGMT = 0.0
  DSTRange=(88.0, 300.0, 1996, 9999) // approximation of UK summer time (last Sunday in March to last Sunday in October)

  // Cut track penalty thresholds, as on the sample track
  CutLeavingThresh = 2
  CutJoiningThresh = 0.95
  CutPassPenalty = 0.7
  CutTimeRatioMax = 0.95
  CutTimeRatioPenalty = 0.375
  CutSecondsSaved = 0.675
  CutWorstYawPenalty = 1.5
  CutDirectionalPenalty = 1.0
  CutWarningThresh = 1.6
  CutStopGoThresh = 3.0

  SettingsFolder = {track_name}
  SettingsCopy = {layout}.svm
  SettingsAI = {layout}.svm
}}
"""


def track_map(xy, size, fg, bg, line_frac=0.012, title=None):
    """Plan view of the centreline as an RGBA image: fg line on bg (bg alpha 0 = transparent)."""
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from PIL import Image

    w, h = size
    fig = plt.figure(figsize=(w / 100, h / 100), dpi=100)
    fig.patch.set_alpha(0)
    ax = fig.add_axes([0.08, 0.08, 0.84, 0.84] if not title else [0.04, 0.1, 0.56, 0.8])
    ax.set_axis_off()
    pts = np.vstack([xy, xy[:1]])
    ax.plot(pts[:, 0], pts[:, 1], color=fg, lw=max(1.5, min(w, h) * line_frac), solid_capstyle="round",
            solid_joinstyle="round")
    ax.plot(*xy[0], "o", color="white", ms=max(2, min(w, h) * 0.03), mec="black")  # start/finish
    ax.set_aspect("equal")
    if title:
        fig.text(0.64, 0.56, title, color="white", fontsize=h / 30, fontweight="bold", va="center")
        fig.text(0.64, 0.48, "Middlesbrough, UK", color="#cccccc", fontsize=h / 50, va="center")
    fig.canvas.draw()
    fg_img = Image.frombuffer("RGBA", fig.canvas.get_width_height(), fig.canvas.buffer_rgba()).copy()
    plt.close(fig)
    out = Image.new("RGBA", fg_img.size, bg)
    out.alpha_composite(fg_img)
    return out.resize(size)


def write_icons(centreline_csv, layout_dir, root, folder, layout, track_name):
    """Track-map images in the places and sizes the sample track has them."""
    import csv
    import numpy as np

    rows = list(csv.DictReader(open(centreline_csv)))
    xy = np.array([[float(r["x"]), -float(r["z"])] for r in rows])  # east, north
    made = []

    def dds(img, path):
        write_dds(np.asarray(img.convert("RGBA")), path)
        made.append(path)

    def save(img, path, fmt):
        img.save(path, fmt)
        made.append(path)

    dds(track_map(xy, (512, 512), "white", (40, 40, 40, 255)), root / f"{folder}Icon.dds")
    save(track_map(xy, (102, 87), "white", (200, 20, 20, 255), 0.025), layout_dir / f"{layout}icon.tga", "TGA")
    dds(track_map(xy, (512, 512), "#f0d000", (40, 40, 40, 255)), layout_dir / f"{layout}SMicon.dds")
    save(track_map(xy, (190, 128), "#f0d000", (0, 0, 0, 0), 0.02), layout_dir / f"{layout}Thmb.tga", "TGA")
    save(track_map(xy, (1920, 1080), "#e05030", (25, 25, 30, 255), 0.006, title=track_name).convert("RGB"),
         layout_dir / f"{layout}_loading.jpg", "JPEG")
    return made


def placeholder_copies(ref, layout_dir, layout):
    """Copy the sample layout's camera, weather and RealRoad preset files, renamed for this layout,
    unless this layout already has its own. They're placeholders: the cameras sit at the sample track's
    positions until replaced."""
    sample_gdb = next((p for p in ref.rglob("*") if p.suffix.lower() == ".gdb"), None)
    if sample_gdb is None:
        return []
    stem, made = sample_gdb.stem, []
    for src in sample_gdb.parent.iterdir():
        ext = src.suffix.lower()
        if ext in (".cam", ".wet"):
            dst = layout_dir / f"{layout}{src.suffix}"
        elif ext == ".rrbin":
            dst = layout_dir / src.name
        else:
            continue
        if not any(p.suffix.lower() == ext and (ext == ".rrbin" and p.name == src.name or ext != ".rrbin")
                   for p in layout_dir.iterdir()):
            shutil.copy2(src, dst)
            made.append(dst)
    return made


def control_clone(ref, out, name="ZZTestA"):
    """An exact copy of the sample track under a new name, as a control: if even this doesn't show in
    Dev Mode's track list, the problem isn't in our files."""
    dst = out / name
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(ref, dst)
    gdb = next(p for p in dst.rglob("*") if p.suffix.lower() == ".gdb")
    old_layout = gdb.stem
    new_layout = f"{name}_Layout"
    layout_dir = gdb.parent.rename(gdb.parent.with_name(new_layout))
    for f in list(layout_dir.iterdir()):
        if f.stem.lower().startswith(old_layout.lower()):
            f.rename(f.with_name(new_layout + f.name[len(old_layout):]))
    gdb = layout_dir / f"{new_layout}{gdb.suffix}"
    text = gdb.read_bytes().decode("latin-1")
    text = re.sub(rf"^{re.escape(old_layout)}", new_layout, text, count=1, flags=re.I)
    text = re.sub(r"(TrackName\s*=).*", r"\1 ZZ Test A (sample copy)", text)
    text = re.sub(r"(VenueName\s*=).*", r"\1 ZZ Test A", text)
    gdb.write_bytes(text.encode("latin-1"))
    return dst


def write_crlf(path, text):
    """Write with Windows line endings, byte for byte. (write_text would translate "\n" again on
    Windows, turning "\r\n" into "\r\r\n", which rF2 can't parse.)"""
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    Path(path).write_bytes("\r\n".join(lines).encode("ascii", errors="replace"))


def instance_blocks(scn_text):
    """Every `Instance=... { ... }` block from an exported .scn, as text (braces balanced)."""
    blocks, pos = [], 0
    for m in re.finditer(r"Instance\s*=\s*[^\s{]+\s*\{", scn_text):
        if m.start() < pos:
            continue
        depth, i = 1, m.end()
        while depth and i < len(scn_text):
            depth += {"{": 1, "}": -1}.get(scn_text[i], 0)
            i += 1
        blocks.append(scn_text[m.start():i])
        pos = i
    return blocks


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--gmt", default="GMT", help="folder with the 3DSimED export (.gmt files and the .scn)")
    ap.add_argument("--scn", help="the exported .scn (default: the only .scn in --gmt)")
    ap.add_argument("--textures", default="build/textures")
    ap.add_argument("--summary", default="build/summary.json")
    ap.add_argument("--reference", default="reference/Joesville", help="ModDev sample track folder")
    ap.add_argument("--out", default="dist/Locations", help="Locations folder to write into")
    ap.add_argument("--folder", default="TeessideKarting")
    ap.add_argument("--layout", default="Teesside_Karting")
    ap.add_argument("--track-name", default="Teesside Karting")
    ap.add_argument("--venue", default="Teesside Motorsports")
    ap.add_argument("--centreline", default="build/centreline.csv", help="for the track-map icons")
    ap.add_argument("--control-clone", action="store_true",
                    help="also write ZZTestA, an exact renamed copy of the sample track, as a test")
    ap.add_argument("--no-placeholder-aiw", action="store_true",
                    help="don't copy the sample track's AIW when the layout has none")
    args = ap.parse_args()

    gmt_dir, ref = Path(args.gmt), Path(args.reference)
    scn_path = Path(args.scn) if args.scn else next(iter(sorted(gmt_dir.glob("*.scn"))), None)
    if scn_path is None:
        sys.exit(f"no .scn in {gmt_dir}")
    tdf = next(iter(sorted(ref.glob("*.tdf"))), None)
    sky = next((p for p in (ref / "Assets" / "GMT").glob("*") if p.name.lower() == "skyboxi.gmt"), None)
    sky_tex = next((p for p in (ref / "Assets" / "Maps").glob("*") if p.name.lower() == "bka.dds"), None)
    if not (tdf and sky and sky_tex):
        sys.exit(f"sample track files not found under {ref} (need *.tdf, Assets/GMT/skyboxi.gmt, "
                 f"Assets/Maps/BKA.DDS)")

    root = Path(args.out) / args.folder
    gmt_out, maps_out, layout_out = root / "Assets" / "GMT", root / "Assets" / "Maps", root / args.layout
    for d in (gmt_out, maps_out, layout_out):
        d.mkdir(parents=True, exist_ok=True)

    gmts = sorted(gmt_dir.glob("*.gmt"))
    for g in gmts:
        shutil.copy2(g, gmt_out / g.name)
    shutil.copy2(sky, gmt_out / "SkyBoxi.gmt")
    textures = sorted(Path(args.textures).glob("*.dds"))
    for t in textures:
        shutil.copy2(t, maps_out / t.name)
    shutil.copy2(sky_tex, maps_out / sky_tex.name)
    shutil.copy2(tdf, root / f"{args.folder}.tdf")

    # Scene: sample-track header with our search paths, then the exported instances with the
    # right collision flags (patched again here in case the export wasn't), then the sky.
    up = args.folder.upper()
    search = "\n".join(f"SearchPath={p}" for p in
                       (".", up, f"{up}\\{args.layout.upper()}", f"{up}\\ASSETS\\GMT", f"{up}\\ASSETS\\MAPS"))
    exported, _ = patch(scn_path.read_text(errors="replace"))
    # 3DSimED writes "VisGroups=(32)ReflectPlane=..."; the sample track separates them with a space.
    blocks = [re.sub(r"\)(?=[A-Za-z])", ") ", b) for b in instance_blocks(exported)]
    scn = SCN_HEADER.format(search_paths=search) + "\n".join(blocks) + "\n" + SKY_INSTANCE
    write_crlf(layout_out / f"{args.layout}.scn", scn)

    summary = json.loads(Path(args.summary).read_text())
    lon, lat = Transformer.from_crs("EPSG:27700", "EPSG:4326", always_xy=True).transform(*summary["origin_bng"])
    km = summary["length_m"] / 1000
    gdb = GDB.format(layout=args.layout, folder=args.folder, track_name=args.track_name, venue=args.venue,
                     km=km, miles=km / 1.609344, lat=lat, lon=lon, alt=summary["origin_alt_m"])
    write_crlf(layout_out / f"{args.layout}.gdb", gdb)

    # rF2 only lists a layout that has an AIW (AI line, grid, garages) next to its .gdb and .scn. Until a
    # Teesside one is recorded, use the sample track's as a placeholder; never overwrite a real one.
    aiw = layout_out / f"{args.layout}.AIW"
    existing = [p for p in layout_out.glob("*") if p.suffix.lower() == ".aiw"]
    sample_aiw = next((p for p in ref.rglob("*") if p.suffix.lower() == ".aiw"), None)
    placeholder = False
    if not existing and not args.no_placeholder_aiw:
        if sample_aiw is None:
            sys.exit(f"no .AIW under {ref} to use as a placeholder")
        shutil.copy2(sample_aiw, aiw)
        placeholder = True

    icons = write_icons(args.centreline, layout_out, root, args.folder, args.layout, args.track_name)
    copies = placeholder_copies(ref, layout_out, args.layout)
    clone = control_clone(ref, Path(args.out)) if args.control_clone else None

    names = {re.match(r"Instance\s*=\s*(\S+)", b).group(1) for b in blocks}
    missing = sorted({"xfinish", "xsector1", "xsector2", "xpitin", "xpitout"} - names)
    print(f"Wrote {root}")
    print(f"  {len(gmts)} meshes + sky, {len(textures)} textures + sky texture, {len(blocks)} instances in the scene")
    print(f"  track info: {args.track_name}, {km:.3f} km, lat {lat:.5f} lon {lon:.5f}")
    if placeholder:
        print(f"  AIW: PLACEHOLDER copied from {sample_aiw.name} so rF2 lists the track. Its racing line, grid and "
              f"garages are the sample track's, not Teesside's; replace it with a recorded one.")
    elif existing:
        print(f"  AIW: kept existing {existing[0].name}")
    print(f"  icons/thumbnail/loading screen: {', '.join(p.name for p in icons)}")
    if copies:
        print(f"  placeholders from the sample track: {', '.join(p.name for p in copies)}")
    if clone:
        print(f"  control track: {clone} (shows as 'ZZ Test A (sample copy)')")
    if missing:
        print(f"WARNING: the export has no {', '.join(missing)}; rF2 needs these timing/pit gates", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
